DROP table IF  EXISTS entrenadores  ;
create TABLE ENTRENADORES(
ID INT AUTO_INCREMENT PRIMARY KEY,
NOMBRE VARCHAR(100) NOT NULL);
INSERT INTO ENTRENADORES (NOMBRE) values ('PEDRO');
INSERT INTO ENTRENADORES (NOMBRE) values ('JUAN');
